- name: cloudalchemy.node-exporter
- name: cloudalchemy.snmp-exporter
- name: cloudalchemy.blackbox-exporter
- name: cloudalchemy.prometheus
- name: cloudalchemy.alertmanager
- name: cloudalchemy.grafana
- name: cloudalchemy.mysqld_exporter
- name: micczu1.ansible_process_exporter
- name: micczu1.ansible_sql_exporter
- name: micczu1.ansible_conntrack_exporter
