---
# defaults
# node_exporter_version: 0.17.0
# node_exporter_web_listen_address: "0.0.0.0:9100"

# node_exporter_system_group: "node-exp"
# node_exporter_system_user: "{{ node_exporter_system_group }}"

# node_exporter_textfile_dir: "/var/lib/node_exporter"
node_exporter_textfile_list:
  - apt.sh
  - yum.sh
  - directory-size.sh

node_exporter_enabled_collectors:
  - systemd
#  - devstat # Dragonfly, FreeBSD
  - processes
  - tcpstat
  - logind
  - ksmd
  - mountstats
  - interrupts
  - buddyinfo
  - qdisc
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"
  - filesystem:
      ignored-mount-points: "^/(sys|proc|dev)($|/)"
      ignored-fs-types: "^(sys|proc|auto)fs$"

node_exporter_disabled_collectors:
  - zfs
